### PR TITLE
Do not use global LayoutVariables

### PR DESCRIPTION
**Pull request by lesyk**

### CODE REVIEW

**Comment by lesyk** [comment]
Any updates?

**Comment by lesyk** [comment]
More fixes.

**Comment by lesyk** [comment]
@reilem 704ec4e is pretty bad way to fix it, but for not I think it will work. Definitely the way how all day events are build need to be re-written to autolayout.

**Comment by reilem** [comment]
I've finally had the chance to look at this in detail. Sorry for the delay. I like the idea of removing the "global static variables" method of storing layout fields. However attaching them all to DayScrollView isn't a great solution. Since some of those fields, such as top bar height are not really the dayScrollView's responsibility. Those are more related to the WeekView  because the weekView is the one that actually stores the topBar.

Seeing as right now many of the layout variables are being stored double (once in LayoutVariables and once in the View themselves). It might be best to just eliminate the LayoutVariables class entirely and try to adopt a completely different strategy.

I'm going to start working on a fix for a bug surrounding the all day events causing screen jitter. Perhaps while I fix this I can start thinking about a different way to implement the LayoutVariables class.

**Comment by reilem** [comment]
I finally got round to fixing this issue. Thank you for this PR @lesyk, it gave me some inspiration while making PR #22. All global variables should be removed, and I shoved all the variables into classes that needed them the most. If you find anything weird or could be better feel free to let me know. I will be closing this PR for now. Thanks again!

**Pull request closed without merging**
