### PR TITLE
Add: project to build as a framework

### PR DESCRIPTION
**Pull request by lesyk**

### CODE REVIEW

**Comment by lesyk** [comment]
Any thoughts on this?

**Comment by reilem** [comment]
Looks fine to me, this mainly enables the project to be built as framework right? My only concern is if the extra clutter is worth it and that the license contains the original company name. I'll try to have a proper look at the project structure when I have time.

**Comment by lesyk** [comment]
1. Looks fine to me, this mainly enables the project to be built as framework right?
Initially yes. However, now I added two additional properties: todayViewColor, and allDayEventsSpreadOnX.

1. My only concern is if the extra clutter is worth it and that the license contains the original company name.
a) It depends what do you mean under extra clutter. If working example project + ability to use this library with Cathage + two additional properties is something, which you believe is useless - than that is way. If you think is something which enables more people to contribute and use this project - then let us collaborate more.
b) I rolled back all comments where I removed credentials, including the License file.

1. I'll try to have a proper look at the project structure when I have time.
No problems. If you have questions, or comments - I am here to help...

**Comment by reilem** [comment]
Loaded up your fork into XCode and everything looks pretty good, the folder structure is definitely an improvement. 😄 However would it be possible for the todayViewColor default to be optional and not "Clear" as it is now. So that if it is null just the standard weekend/regular day color is used. Currently the default makes the today day view cell transparent which isn't ideal. If a user would just like the standard color to appear then this feature currently makes that a little difficult since they would then manually have to determine if today is a weekend or not to then provide the correct color.

Also you seem to have increased the minimum deployment to 10.0, is this needed? I would rather not increase minimum deployment unless it is absolutely necessary. Some of out users still use 9.0 and it would be unfair to them to force them to update for no reason.

**Comment by lesyk** [comment]
Will make changes a bit later... Thank you for feedback.

**Comment by lesyk** [comment]
Fixed.

**Pull request merged**
